### ISSUE TITLE
Message paging issues

### ISSUE THREAD

**Issue by sudha53633** [bminer/node-twilio-api#19]
Hi there,

I could fetch 1000 messages from twilio api, after that i'm getting error messages resource not fount.

How do i get more messages, the code which i've used is as below.

Please help me here...

var twilio = require('twilio');
var accountSid = 'ACxxx';
var authToken = 'yyy';
var client = twilio(accountSid, authToken);
var baseUrl = 'https://' + accountSid + ': '+ authToken + '@' + client.host;
function handleResults(err, data) {
if (err) {
return console.error(err);
}
// do something with current page...
console.log(data.messages);
if (data.numPages > 1) {
// request the next page in the janky way
client.request({
url: baseUrl + data.nextPageUri,
qs: {
// need to use actual REST API parameter - this method does not
// massage inputs, it's pretty much a direct passthrough to
// the underlying HTTP client (mikeal/request)
PageSize: 1000
}
}, handleResults);
}
}
// fetch resources normally
client.listMessages({
pageSize: 1000
}, handleResults);

Thanks,
Sudhakar

**Comment by bminer** [comment]
This issue is related to the official Twilio repo.

@sudha53633 - You posted an issue to the wrong repository.  Check out https://github.com/twilio/twilio-node
