### ISSUE TITLE
CB from Call.record() never called

### ISSUE THREAD

**Issue by hypervillain** [bminer/node-twilio-api#21]
I can't manage to get both cb() and cbifempty() working, after making a phone call to Twilio.

Here is my actual code :

```
function emptyCB(a,v) {
  console.log("EMPTY", a, v)
}

function functionCB(call, recordingUrl, recordingDuration, input) {
  console.log(call, recordingUrl, recordingDuration, input)
}

app.post('/voice', function (req, res) {
  var twiml = new twilio.TwimlResponse();
  twiml.say('Hello. This is my webtask to record your call.');

  twiml.record(functionCB, {maxLength : "50"}, emptyCB);

  twiml.hangup();

  res.type('text/xml');
  res.send(twiml.toString());
});
```

Any idea why this isn't working?

Thanks!

**Comment by bminer** [comment]
Yes.  After the recording completes, Twilio will contact your server using the auto-generated callback ID from the `twiml`.  But, you need to ensure that you are listening for that callback in another route.

The easiest way to do this is to setup the Twilio middleware for intercepting these HTTP requests.  Then, your callback will be automatically called.

See https://github.com/bminer/node-twilio-api/#basic-usage

Closing this issue for now, but please feel free to write back here if you have any more questions.

**Comment by hypervillain** [comment]
Believing the callback would be accessible to Twilio was a bit dumb from me ahah.

This one makes more sense indeed :

`twiml.record({maxLength : "50", recordingStatusCallback: "anAbsoluteUrlToMyOwnServer"});`

Thanks!

**Comment by bminer** [comment]
Yes, I forgot you could explicitly set `recordingStatusCallback`. :)

**Comment by hypervillain** [comment]
There is also an action parameter that you need to set explicitly if you don't want Twilio to call the current route twice!
