### ISSUE TITLE
Clarification with app registration

### ISSUE THREAD

**Issue by RaphiePS** [bminer/node-twilio-api#5]
Hi! I'm quite excited to use the library, but I'm running into an issue with registering an application. Do I use the SID of an existing app? When I try that, it throws "Error: This application cannot be registered because required fields are missing or invalid."

The code is literally copied from the readme, with the SID's replaced. Thanks!

**Comment by bminer** [comment]
Sorry.  I should probably clarify this in the documentation.  Your application needs to provide a 'VoiceUrl', 'StatusCallback', 'SmsUrl', and 'SmsStatusCallback'.  Do you know if all of those are entered?

**Comment by RaphiePS** [comment]
Great, thanks for the swift response. Looking forward to using the library!

On Wed, Mar 14, 2012 at 11:11 AM, Blake Miner <
reply@reply.github.com

**Comment by bminer** [comment]
You're welcome. Please let me know what you think of the lib, and if you run into any other issues, please let me know. It's a work-in-progress, but starting to gain some traction.  Thanks!

I'm closing this issue.  :)

**Comment by samuelhough** [comment]
Would it be possible to have the isValid check, throw the missing parameters up along with the message?  I had to parse through the code as well to try and figure out what was wrong.
